import { ColorTokens, DesignSystem } from "@/types/design-system";
import { hexToHsl } from "@/utils/contrast-utils";
import { readableOn } from "@/utils/brand-system";

/* ------------------------------------------------------------------ *
 * Exporters over the unified DesignSystem.                           *
 *                                                                    *
 * Unlike the color-only Brand System exporters, these emit every     *
 * token group (color light/dark, chart, type, space, radius, shadow) *
 * and add a first-class shadcn/ui theme.                             *
 * ------------------------------------------------------------------ */

const hx = (hex: string) => hex.slice(0, 7).toLowerCase();

/** Convert #rrggbb → "h s% l%" (shadcn's channel format for hsl(var(--x))). */
function hslChannels(hex: string): string {
  const [h, s, l] = hexToHsl(hex.slice(0, 7));
  return `${h} ${s}% ${l}%`;
}

/** px → rem string (16px base). */
function rem(px: number): string {
  return `${+(px / 16).toFixed(4)}rem`;
}

function headerLines(ds: DesignSystem, prefix: string): string {
  return [
    `${ds.name} — Design System`,
    `Generated by Palattes`,
    `Modes: light + dark (default: ${ds.mode})`,
  ]
    .map((l) => `${prefix}${l}`)
    .join("\n");
}

/* ------------------------------------------------------------------ *
 * Full CSS theme — all token groups, both modes.                     *
 * ------------------------------------------------------------------ */

function colorVarLines(color: ColorTokens, indent: string): string {
  return Object.entries(color)
    .map(([k, v]) => `${indent}--${k}: ${hx(v)};`)
    .join("\n");
}

function nonColorVarLines(ds: DesignSystem, indent: string): string {
  const t = ds.tokens;
  const lines: string[] = [];
  lines.push(`${indent}/* Typography */`);
  lines.push(`${indent}--font-sans: ${t.typography.sans};`);
  if (t.typography.mono)
    lines.push(`${indent}--font-mono: ${t.typography.mono};`);
  t.typography.scale.forEach((px, i) =>
    lines.push(`${indent}--text-${i}: ${rem(px)};`),
  );
  lines.push(`${indent}--leading-base: ${t.typography.lineHeight};`);
  lines.push(`${indent}--tracking-base: ${t.typography.tracking}em;`);
  lines.push(`${indent}/* Spacing */`);
  t.space.forEach((px, i) => lines.push(`${indent}--space-${i}: ${rem(px)};`));
  lines.push(`${indent}/* Radius */`);
  lines.push(`${indent}--radius-sm: ${t.radius.sm}px;`);
  lines.push(`${indent}--radius-md: ${t.radius.md}px;`);
  lines.push(`${indent}--radius-lg: ${t.radius.lg}px;`);
  lines.push(`${indent}--radius-full: ${t.radius.full}px;`);
  lines.push(`${indent}/* Elevation */`);
  t.shadow.forEach((s, i) => lines.push(`${indent}--shadow-${i + 1}: ${s};`));
  lines.push(`${indent}/* Chart */`);
  t.chart.forEach((c, i) => lines.push(`${indent}--chart-${i + 1}: ${hx(c)};`));
  return lines.join("\n");
}

export function exportCssTheme(ds: DesignSystem): string {
  return `:root {
  /*
${headerLines(ds, "  ")}
  */
${colorVarLines(ds.tokens.color.light, "  ")}
${nonColorVarLines(ds, "  ")}
}

@media (prefers-color-scheme: dark) {
  :root {
${colorVarLines(ds.tokens.color.dark, "    ")}
  }
}

[data-theme="dark"] {
${colorVarLines(ds.tokens.color.dark, "  ")}
}

[data-theme="light"] {
${colorVarLines(ds.tokens.color.light, "  ")}
}`;
}

/* ------------------------------------------------------------------ *
 * shadcn/ui theme — canonical tokens mapped to shadcn variables.     *
 * ------------------------------------------------------------------ */

/** Map our canonical color tokens onto shadcn's semantic variable set. */
function shadcnVars(c: ColorTokens): Record<string, string> {
  const g = (k: string, fallback = "#000000") => c[k] ?? fallback;
  return {
    background: g("bg-base"),
    foreground: g("text-primary"),
    card: g("surface"),
    "card-foreground": g("text-primary"),
    popover: g("bg-elevated"),
    "popover-foreground": g("text-primary"),
    primary: g("brand-primary"),
    // Fall back to a computed readable foreground when the source token set has
    // no explicit on-color (e.g. the studio's role model), so shadcn's
    // *-foreground vars stay legible instead of defaulting to black.
    "primary-foreground": c["on-brand"] ?? readableOn(g("brand-primary")),
    secondary: g("brand-secondary"),
    "secondary-foreground": readableOn(g("brand-secondary")),
    muted: g("surface-hover"),
    "muted-foreground": g("text-muted"),
    accent: g("brand-accent"),
    "accent-foreground": c["on-accent"] ?? readableOn(g("brand-accent")),
    destructive: g("state-error"),
    "destructive-foreground": c["on-error"] ?? readableOn(g("state-error")),
    border: g("border-subtle"),
    input: g("border-strong"),
    ring: g("focus-ring"),
  };
}

function shadcnBlock(c: ColorTokens, chart: string[], indent: string): string {
  const vars = shadcnVars(c);
  const lines = Object.entries(vars).map(
    ([k, v]) => `${indent}--${k}: ${hslChannels(v)};`,
  );
  chart
    .slice(0, 5)
    .forEach((hex, i) =>
      lines.push(`${indent}--chart-${i + 1}: ${hslChannels(hex)};`),
    );
  return lines.join("\n");
}

/**
 * shadcn/ui `globals.css` theme. Emits HSL channel triplets (the classic
 * shadcn format consumed via `hsl(var(--token))`), with light in `:root`,
 * dark in `.dark`, chart colors, and the base radius.
 */
export function exportShadcn(ds: DesignSystem): string {
  return `/* ${ds.name} — shadcn/ui theme (generated by Palattes) */
@layer base {
  :root {
${shadcnBlock(ds.tokens.color.light, ds.tokens.chart, "    ")}
    --radius: ${rem(ds.tokens.radius.md)};
  }

  .dark {
${shadcnBlock(ds.tokens.color.dark, ds.tokens.chart, "    ")}
  }
}`;
}

/* ------------------------------------------------------------------ *
 * Tailwind — reference the CSS vars so both themes work at runtime.  *
 * ------------------------------------------------------------------ */

export function exportTailwindTheme(ds: DesignSystem): string {
  const colorEntries = Object.keys(ds.tokens.color.light)
    .map((k) => `        "${k}": "var(--${k})",`)
    .join("\n");
  const chartEntries = ds.tokens.chart
    .map((_, i) => `        "chart-${i + 1}": "var(--chart-${i + 1})",`)
    .join("\n");
  const fontSize = ds.tokens.typography.scale
    .map((_, i) => `        "${i}": "var(--text-${i})",`)
    .join("\n");
  const spacing = ds.tokens.space
    .map((_, i) => `        "${i}": "var(--space-${i})",`)
    .join("\n");
  const shadow = ds.tokens.shadow
    .map((_, i) => `        "${i + 1}": "var(--shadow-${i + 1})",`)
    .join("\n");
  return `/** @type {import('tailwindcss').Config} */
// ${ds.name} Design System — pair with the CSS theme export (light + dark vars).
module.exports = {
  theme: {
    extend: {
      colors: {
${colorEntries}
${chartEntries}
      },
      fontFamily: {
        sans: "var(--font-sans)",${
          ds.tokens.typography.mono ? '\n        mono: "var(--font-mono)",' : ""
        }
      },
      fontSize: {
${fontSize}
      },
      spacing: {
${spacing}
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        full: "var(--radius-full)",
      },
      boxShadow: {
${shadow}
      },
    },
  },
};`;
}

/* ------------------------------------------------------------------ *
 * JSON — full token document, all groups + both modes.               *
 * ------------------------------------------------------------------ */

export function exportTokensJson(ds: DesignSystem): string {
  const colorObj = (c: ColorTokens) => {
    const o: Record<string, { $value: string; $type: "color" }> = {};
    for (const [k, v] of Object.entries(c))
      o[k] = { $value: hx(v), $type: "color" };
    return o;
  };
  return JSON.stringify(
    {
      name: `${ds.name} Design System`,
      generatedBy: "Palattes",
      defaultMode: ds.mode,
      source: ds.source,
      brandKit: ds.brandKit,
      color: {
        light: colorObj(ds.tokens.color.light),
        dark: colorObj(ds.tokens.color.dark),
      },
      chart: ds.tokens.chart.map(hx),
      typography: ds.tokens.typography,
      space: ds.tokens.space,
      radius: ds.tokens.radius,
      shadow: ds.tokens.shadow,
      border: ds.tokens.border,
      density: ds.tokens.density,
    },
    null,
    2,
  );
}
